name: Create a STEP  version of the main.csg file
on:
  push:
    branches:
      - main
      #- develop

jobs:
  file_convert:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check if main.scad has changed
        id: check_changes
        run: |
          git fetch
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          if [[ ! ${CHANGED_FILES} =~ main\.scad$ ]]; then
            echo "main.scad file hasn't changed. Skipping the action."
            exit 0
          fi

      - name: Install FreeCAD and OpenSCAD ALT Import #there is a weird bug that persists still in the 0.20.2 version of FreeCAD installed via apt
        run: |
          sudo apt install -y freecad
          cd /usr/share/freecad
          git clone https://github.com/KeithSloan/OpenSCAD_Alt_Import.git

      - name: Convert file to STEP format
        run: |


      - name: Commit and push changes  
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add main.step
          git commit -m "Update STEP and CSG versions based on new main.scad file."
          git push

